USE [DBPROVIS_PRE]
GO

/****** Object:  Table [dbo].[TPASOSOP]    Script Date: 05/29/2019 14:03:30 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TPASOSOP](
	[COD_SEC_OPERACION] [decimal](9, 0) NOT NULL,
	[SEC_PASO] [decimal](9, 0) NOT NULL,
	[PROC_ORIGEN] [char](250) NULL,
	[PROC_ZONE] [char](250) NULL,
	[DESC_LOG] [char](250) NULL,
	[DESC_PASO] [char](250) NULL,
	[VISIBLE] [decimal](1, 0) NULL,
	[SQL_CODE_ERROR] [decimal](4, 0) NULL,
	[DESC_ERROR] [char](250) NULL,
	[TIME_STAMP] [nvarchar](30) NULL,
 CONSTRAINT [XPKTPASOSOP] PRIMARY KEY NONCLUSTERED 
(
	[COD_SEC_OPERACION] ASC,
	[SEC_PASO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


USE [DBPROVIS_PRE]
GO

/****** Object:  Table [dbo].[TLOGERRO]    Script Date: 05/29/2019 14:42:08 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TLOGERRO](
	[COD_SEC_ERROR] [decimal](9, 0) IDENTITY(1,1) NOT NULL,
	[COD_ERROR] [decimal](6, 0) NULL,
	[DES_ERROR] [char](250) NULL,
	[DES_PROCEDIMIENTO] [char](40) NULL,
	[FEC_ERROR] [datetime] NULL,
	[COD_SEC_PROVISION] [decimal](9, 0) NULL,
	[NUM_LINEA_ERROR] [decimal](4, 0) NULL,
 CONSTRAINT [XPKTLOGERRO] PRIMARY KEY NONCLUSTERED 
(
	[COD_SEC_ERROR] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

USE [DBPROVIS_PRE]
GO

/****** Object:  Table [dbo].[TOPERPRV]    Script Date: 05/29/2019 14:42:38 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TOPERPRV](
	[COD_SEC_OPERACION] [decimal](9, 0) IDENTITY(1,1) NOT NULL,
	[COD_TIPO_OPERACION] [decimal](9, 0) NULL,
	[FEC_OPERACION] [datetime] NULL,
	[COD_ESTADO_OPERACION] [decimal](3, 0) NULL,
	[FEC_VALIDEZ_DATOS] [datetime] NULL,
	[FEC_ALTA] [datetime] NULL,
	[FEC_BAJA] [datetime] NULL,
	[FEC_ULTMOD] [datetime] NULL,
	[NOM_USUARIO_ALTA] [char](20) NULL,
	[NOM_USUARIO_BAJA] [char](20) NULL,
	[NOM_USUARIO_ULTMOD] [char](20) NULL,
	[COD_CONCURRENCIA] [decimal](3, 0) NULL,
	[COD_SEC_PROVISION] [decimal](9, 0) NULL,
 CONSTRAINT [XPKTOPERPRV] PRIMARY KEY NONCLUSTERED 
(
	[COD_SEC_OPERACION] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO
